### ISSUE TITLE
Transforms Summary

### ISSUE THREAD

**Issue by ttaa9** [bayesiains/nflows#18]
Sorry if it is already here, but do you have a summary somewhere of the set of `transforms` (i.e., bijective mapping layers) that you have implemented? A short list of them, perhaps along with the papers they're from and how to use/stack them in practice, would be quite helpful. 

I suppose this is related to issue #3.

This looks like a fantastic repo. Thanks for putting it up!

**Comment by arturbekasov** [comment]
Hi @ttaa9,

We don't have a good summary of the set of implemented transforms, unfortunately. You're right in that this should be one of the deliverables of the wider effort to improve documentation (which indeed starts with #3). Contributions are always welcome! 🙂 

If it helps, we've tried to keep all the classes in `nsf.transforms` well-documented, pointing to papers whenever possible.

Thanks,

Artur
