### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by ttaa9** [bayesiains/nflows#27]
Sorry if I missed it, but how would you prefer `nflows` to be cited?

A bibtex entry for example would be useful. :)

**Comment by arturbekasov** [comment]
Good suggestion -- thanks! I've now [added](https://github.com/bayesiains/nflows#citing-nflows) info on citing `nflows` to README.md.

**Comment by ttaa9** [comment]
Thanks! Note that you're missing an end-brace in the current version, under `title`, though. :)

**Comment by arturbekasov** [comment]
> Thanks! Note that you're missing an end-brace in the current version, under `title`, though. :)

Oops, good catch — fixed! :-) Thanks!
