### ISSUE TITLE
Adding UMNN as a monotonic transformer? 

### ISSUE THREAD

**Issue by AWehenkel** [bayesiains/nflows#28]
Hi there!
Thanks for this very nice library!
Would you be up for me to add Unconstrained Monotonic Neural Networks to your library?
Regards,
Antoine

**Comment by arturbekasov** [comment]
Hi Antoine!

Delighted if you're finding the library useful. :-) 

Having UMMN in the library would be great. At the moment we only have affine and splined-based monotonic transformers.

What we do at present is for each type of the monotonic function we implement a coupling transform version (see `nflows/transforms/coupling.py`) and an autoregressive transform version (see `nflows/transforms/autoregressive.py`). It's likely we could've done more thinking to decouple the monotonic transformer from the conditioner so you wouldn't have to implement the two versions, but here we are.

UMMN would be somewhat unique in that other monotonic transformers we have admit an analytic inverse. All of the transforms implement the `inverse()` method: for UMMN this would presumably contain the bijective search loop?

Anything else I can help with: please let me know.

Cheers,

Artur

**Comment by AWehenkel** [comment]
Hi Arthur,

Thanks for your fast and useful answer. I just made a pull request with my implementation. Could you check it when you have time?
Anyway, I think I can close the issue here.

Thanks!

Antoine
