### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by arturbekasov** [bayesiains/nflows#3]
At the moment the framework is difficult to get started with for newcomers. Without reading the code it's not clear what modules there are and how they're supposed to be used.

To begin with, I think the README could be improved. We should include:
- An overview of the API: the main classes (`Distribution`, `Transformation`, `Flow`) and how they're related.
- An overview of implemented features: what flow/layer types are available.
- A short, didactic snippet of code for creating a simple flow and setting up the optimization.

**Comment by pharringtonp19** [comment]
> At the moment the framework is difficult to get started with for newcomers. Without reading the code it's not clear what modules there are and how they're supposed to be used.
> 
> To begin with, I think the README could be improved. We should include:
> 
> * An overview of the API: the main classes (`Distribution`, `Transformation`, `Flow`) and how they're related.
> * An overview of implemented features: what flow/layer types are available.
> * A short, didactic snippet of code for creating a simple flow and setting up the optimization.

@arturbekasov As someone who just started using this repo (which I think is great), I would be happy to work to try to make it even more accessible to others by adding more examples/whatever you may think is helpful - just let me know. Thanks!

**Comment by arturbekasov** [comment]
The README has improved since this issue was created (though can always be improved further), so closing.
