### ISSUE TITLE
Beginner's question

### ISSUE THREAD

**Issue by famura** [bayesiains/nflows#30]
Hi there,

I am rather new to normalizing flows and recently started looking into your library. Therefore I would like to answer the following question:

In the readme, you append `MaskedAffineAutoregressiveTransform` and then `RandomPermutation`, while in the two moons example you append `ReversePermutation` and then `MaskedAffineAutoregressiveTransform`. Are those two ways equivalent? Which rules does one have to follow when appending transformations?

Best wishes,
Fabio

**Comment by arturbekasov** [comment]
The transformations can be stacked in any way and order, as soon as the shapes are aligned. What works better will depend entirely on the application.
