### ISSUE TITLE
AttributeError: 'int' object has no attribute 'utils'

### ISSUE THREAD

**Issue by ggproRIC** [bayesiains/nflows#43]
from keras.utils import to_categorical
from keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
img_rows, img_cols = 28,28
x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
input_shape = (img_rows, img_cols, 1)
x_test=x_test.astype('float32')
x_train=x_train.astype('float32')
mean=np.mean(x_train)
std=np.std(x_train)
x_test = (x_test-mean)/std
x_train = (x_train-mean)/std

print("counts of x_train : {}, y_train : {}, x_test : {}, y_test : {}".format(
    len(x_train), len(y_train), len(x_test), len(y_test)))
num_classes=10
y_train = k.utils.to_categorical(y_train, num_classes)
y_test = k.utils.to_categorical(y_test, num_classes)
print("counts of x_train : {}, y_train : {}, x_test : {}, y_test : {}".format(
    len(x_train), len(y_train), len(x_test), len(y_test)))
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-d0e465b0d092> in <module>
     16     len(x_train), len(y_train), len(x_test), len(y_test)))
     17 num_classes=10
---> 18 y_train = k.utils.to_categorical(y_train, num_classes)
     19 y_test = k.utils.to_categorical(y_test, num_classes)
     20 print("counts of x_train : {}, y_train : {}, x_test : {}, y_test : {}".format(

AttributeError: 'int' object has no attribute 'utils'

**Comment by arturbekasov** [comment]
Don't see how this is relevant to our package, sorry.
