### ISSUE TITLE
AffineCouplingLayer scale <1.001

### ISSUE THREAD

**Issue by dennisprangle** [bayesiains/nflows#49]
Line 225 of coupling.py can only produce a scale in the interval [0.001,1.001] which is very restrictive. The commented out line 224 produces an interval of roughly [0,3] which seems more generally useful. Or alternatively maybe both types of behaviour could be allowed e.g. through extra class initialization arguments.

(Thanks for the very useful + clear package!)

**Comment by arturbekasov** [comment]
Hi Dennis,

Sorry for a belated response. Glad you're finding the package useful!

Indeed, the parametrization used is rather restrictive. However, empirically we've observed that such parametrization makes the training more stable. In fact, the canonical Glow implementation [does the same](https://github.com/openai/glow/blob/master/model.py#L376), likely for the same reason. You can also see the naive exp parametrization commented out on the [previous line](https://github.com/openai/glow/blob/master/model.py#L375): we've also observed this to be particularly unstable.

I agree this should ideally be configurable with a parameter to the constructor. Unfortunately, I am really low on time these days to implement this myself, but I can commit to reviewing a PR implementing this.

Cheers,

Artur

**Comment by dennisprangle** [comment]
Hi Artur, thanks for the response. I will try to put a PR together over the next few weeks. I think the code should be straightforward, but feedback on what is a good API would be great.
