### ISSUE TITLE
Block Neural Autoregresive Flow

### ISSUE THREAD

**Issue by jecampagne** [bayesiains/nflows#66]
Hello,
do you know if there is an existing implementation of [Block Neural Autoregresive Flow](https://github.com/nicola-decao/BNAF)  (aka B-NAF) in the context of nflows?
Thanks

**Comment by arturbekasov** [comment]
I am not aware of any existing implementations of B-NAF using nflows. Perhaps the original author (owner of the linked repo) will be able to help?
