### ISSUE TITLE
Instability due to division by scale?

### ISSUE THREAD

**Issue by starovoitovs** [bayesiains/nflows#67]
My issue is more of a mathematical nature, in the inverse affine transform one divides by scale

    outputs = (inputs - shift) / scale

The scale is output of softplus + epsilon, which is `1e-3` by default. If my scale is always close to zero, and my network has 5 affine transformations, it's potentially multiplication by a factor of `1e-15`. And I observe samples of such order of magnitude during training/validation. Apart from increase of `1e-3`, is there some less artificial way to avoid this instability?

**Comment by arturbekasov** [comment]
> my scale is always close to zero

Doubt you can avoid under/overflows if this is the case. Besides, you're then working on the boundary of non-invertibility, so I'd expect all sorts of numerical issues. The goal of `epsilon` is to avoid crashes during the (early stages of) training, but we don't expect the network to converge on near-zero scales. My only suggestion would be to try to reparametrize the problem to avoid the need for such drastic transformations.
