### ISSUE TITLE
How to work with categorical input features

### ISSUE THREAD

**Issue by fountaindive** [bayesiains/nflows#74]
Hi, I'm interested in using normalising flows to model tabular data with both continuous and categorical features. Can the `nflows` package handle this?

Many thanks!

**Comment by imurray** [comment]
This library can handle the continuous features, conditioned on the categorical features, which can be provided as context. You'd need to use something else (or extend this library yourself) to handle the categorical features. Then add together the two log probs.

Or as a cheap hack, depending on what you're doing, add noise to the categorical features and model the resulting continuous features.
