### ISSUE TITLE
Using SimpleRealNVP on a 10 features converging to a different std

### ISSUE THREAD

**Issue by yarinbar** [bayesiains/nflows#78]
Hi!
We are using SimpleRealNVP and encountered a strange phenomenon. The flow converges to a seemingly normal distribution:
![image](https://github.com/bayesiains/nflows/assets/37772157/4e576765-2619-4dc7-93d5-2e6cab0f8c3a)

However, when plotting the covariance matrix (that should be I) we get lower variances across the board:
![image](https://github.com/bayesiains/nflows/assets/37772157/e0b32500-09f2-4e8e-8930-8e5222e7a2e0)

When dropping number of features we experience increased variance and when increasing the number of features to 512 the variance drops further and is significantly closer to 0.

We could not figure out what is causing this problem. Any help would be appreciated :D

**Comment by arturbekasov** [comment]
Hmm, not sure what's going on here. Your first plot suggests a variance of ~1 -- are you sure you're estimating the covariance matrix correctly? Unfortunately, we don't have the capacity to help with debugging: let us know if you can track it down to an issue with the package.
