### ISSUE TITLE
Interest in being added as conda-forge feedstock maintainer?

### ISSUE THREAD

**Issue by matthewfeickert** [bayesiains/nflows#83]
:wave: As part of a https://github.com/sbi-dev/sbi/issues/1322 I've added `nflows` to conda-forge (Issue https://github.com/bayesiains/nflows/issues/82): https://github.com/conda-forge/nflows-feedstock/.

[![Conda Version](https://img.shields.io/conda/vn/conda-forge/nflows.svg)](https://anaconda.org/conda-forge/nflows) [![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/nflows.svg)](https://anaconda.org/conda-forge/nflows)

Whenever I add something to conda-forge I like to also make sure that the project maintainers are aware of it and I also like to include them as feedstock maintainers so that they still have the ability to control the distribution of their project source code if they want to. This comes without any expectation of having to actually do the maintenance of the feedstock as it is unfair to expect additional work of project maintainers beyond the source code itself.

* @arturbekasov Would you be interested in being listed as a conda-forge feedstock maintainer?

* Would you be open to a PR that would add conda-forge install instructions using `conda` and/or `pixi` to the README?

**Comment by arturbekasov** [comment]
Hey @matthewfeickert. Thanks for reaching out. Of course, happy to be listed as a maintainer in conda, and happy to merge in conda instructions. Cheers, Artur
